In [17]:
import pandas as pd

# load the breast_cancer dataset from csv
BC_Data = pd.read_csv('Cancer_Data.csv')

# data visualization
print BC_Data.head()
Data=BC_Data.drop('id', axis=1)
Feature=Data.drop('diagnosis', axis=1)
print Feature.describe()   

         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

            ...             radius_worst  texture_worst  perim

In [21]:
import numpy as np
from Data_Process import Data_Process
from time import time
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

if __name__=="__main__":
    
    # data preprocessing
    X, Y=Data_Process().get_data()
    X_train, X_test, y_train, y_test =Data_Process().data_split(X, Y)
    
    # perform four kinds of supervised machine learning algorithm on the data set
    for smla in [LogisticRegression(random_state=0), SVC(random_state=0), DecisionTreeClassifier(random_state=0), RandomForestClassifier(random_state=0)]:
        smla_name = smla.__class__.__name__
        time_results={}    # for calculate the time efficiency

        # data training
        start1 = time()
        smla.fit(X_train, y_train)
        end1 = time()
        time_results['training time'] = end1 - start1

        # make prediction
        start2 = time()
        y_train_pred = smla.predict(X_train)
        y_test_pred = smla.predict(X_test)
        end2 = time()
        time_results['prediction time'] = end2 - start2

        # calculating the metrics
        train_accuracy = 1.0 * np.mean(y_train_pred == y_train)
        test_accuracy = 1.0 * np.mean(y_test_pred == y_test)
        train_fscore = f1_score(y_train, y_train_pred)
        test_fscore = f1_score(y_test, y_test_pred)

        # display the results
        print 'the accuracy of the training set modeled by {} is {}.'.format(smla_name, train_accuracy) 
        print 'the accuracy of the test set modeled by {} is {}.'.format(smla_name, test_accuracy) 
        print 'the F-score of the training set modeled by {} is {}.'.format(smla_name, train_fscore) 
        print 'the F-score of the test set modeled by {} is {}.'.format(smla_name, test_fscore) 

        print 'time consumption of {} is {}'.format(smla_name, time_results)
        print 'confusion matrix of training set of {} is \n{}'.format(smla_name, confusion_matrix(y_train, y_train_pred))
        print 'confusion matrix of test set of {} is \n{}'.format(smla_name, confusion_matrix(y_test, y_test_pred))

the accuracy of the training set modeled by LogisticRegression is 0.960093896714.
the accuracy of the test set modeled by LogisticRegression is 0.958041958042.
the F-score of the training set modeled by LogisticRegression is 0.96834264432.
the F-score of the test set modeled by LogisticRegression is 0.965909090909.
time consumption of LogisticRegression is {'training time': 0.004000186920166016, 'prediction time': 0.0}
confusion matrix of training set of LogisticRegression is 
[[149  10]
 [  7 260]]
confusion matrix of test set of LogisticRegression is 
[[52  1]
 [ 5 85]]
the accuracy of the training set modeled by SVC is 1.0.
the accuracy of the test set modeled by SVC is 0.629370629371.
the F-score of the training set modeled by SVC is 1.0.
the F-score of the test set modeled by SVC is 0.772532188841.
time consumption of SVC is {'training time': 0.031000137329101562, 'prediction time': 0.03099989891052246}
confusion matrix of training set of SVC is 
[[159   0]
 [  0 267]]
confusion m